# Generated by Django 3.1.3 on 2020-11-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.country')),
            ],
        ),
    ]
